import type { Metadata } from "next";

import "./globals.css";
import { AuthContextProvider } from "@/hook/userContext";
import { Toaster } from "react-hot-toast";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          <Toaster/>
        {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
